#!/usr/bin/env python3
"""
browser_export.py — publish the dataset and the *fitted* pipelines as plain
`<script>`-loadable bundles.

Why this exists
---------------
The dashboard has to give identical answers in every hosting mode:

    python app.py            FastAPI serves /api + the static files      (works)
    GitHub Pages / Live      static host: no /api, but fetch() works     (data OK, predictions dead)
    double-click index.html  file://  — fetch() is BLOCKED by browsers   (11-row fallback, predictions dead)

`fetch()` cannot read local files from a `file://` page (opaque origin), and a
static host has no Python process behind `/api/predict/*`. So both the dataset
and the trained models are *also* written as classic scripts, which every
browser is happy to load from disk. The JavaScript engine in `ml_inference.js`
then evaluates the very same trees, medians, scaler and one-hot encoding that
the scikit-learn pipeline uses — no retraining, no approximation, no demo
numbers.

Outputs (all generated — never hand-edited):
    data/apps_bundle.js                 columnar mirror of data/apps.json
    ml/artifacts/browser/models.js      exported pipelines + their real metrics
    ml/artifacts/browser/parity_cases.json   inputs + sklearn outputs (test fixture)

Run:
    python browser_export.py            # regenerate everything
    python browser_export.py --models   # models + parity cases only
    python browser_export.py --data     # dataset bundle only

`clean.py` and `train_models.py` call this automatically, so the bundles can
never drift from the artifacts they were exported from.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data"
ART = ROOT / "ml" / "artifacts"
BROWSER_DIR = ART / "browser"

APPS_JSON = DATA / "apps.json"
APPS_BUNDLE = DATA / "apps_bundle.js"
MODELS_BUNDLE = BROWSER_DIR / "models.js"
PARITY_CASES = BROWSER_DIR / "parity_cases.json"

# Model families the browser engine (ml_inference.js) can evaluate exactly.
# Anything else is skipped — the dashboard then keeps using the Python API
# instead of silently serving an approximation.
SUPPORTED_ESTIMATORS = (
    "GradientBoostingRegressor",
    "GradientBoostingClassifier",
    "DecisionTreeClassifier",
    "DecisionTreeRegressor",
    "LogisticRegression",
)

# Task -> (model key written into the bundle, artifact sub-directory)
TASKS = (
    ("m1_rating", "m1_rating", "regression"),
    ("m2_tier_without_reviews", "m2_tier_without_reviews", "classification"),
    ("m2_tier_with_reviews", "m2_tier_with_reviews", "classification"),
)

_SCALAR_KEYS = (
    "mae", "rmse", "r2", "accuracy", "macro_f1", "weighted_f1",
    "precision", "recall", "f1",
)


class UnsupportedEstimator(RuntimeError):
    """Raised when a pipeline uses a model the JS engine cannot reproduce."""


# --------------------------------------------------------------------------
# serialization helpers
# --------------------------------------------------------------------------
def _num(v):
    """JSON-safe float: NaN/inf become None (never NaN literals — invalid JSON)."""
    if v is None:
        return None
    f = float(v)
    return f if np.isfinite(f) else None


def _js_assign(varname: str, payload) -> str:
    """Serialize `payload` as `<script>`-safe JS that assigns a global.

    The `<` escape stops an app name containing "</script>" from terminating
    the tag early. `allow_nan=False` guarantees valid JSON (NaN/Infinity are
    JS-legal but JSON-illegal, and we never want them anyway).
    """
    text = json.dumps(payload, separators=(",", ":"), allow_nan=False)
    text = text.replace("<", "\\u003c")
    return (
        f"/* Generated by browser_export.py — do not edit.\n"
        f"   Regenerate with: python browser_export.py */\n"
        f"(function (g) {{ g.{varname} = {text}; }})"
        f"(typeof window !== 'undefined' ? window : globalThis);\n"
    )


def _scalar_metrics(test_metrics: dict | None) -> dict:
    """Keep only the lightweight numbers the UI prints.

    `meta.json` also carries the full confusion matrix / per-class tables;
    those are re-read from metrics.json over HTTP and have no place in a
    bundle the browser downloads.
    """
    out = {}
    for k, v in (test_metrics or {}).items():
        if k in _SCALAR_KEYS and isinstance(v, (int, float)) and not isinstance(v, bool):
            out[k] = _num(v)
    return out


# --------------------------------------------------------------------------
# scikit-learn -> plain data
# --------------------------------------------------------------------------
def _tree_arrays(tree) -> dict:
    """Flatten a fitted sklearn tree into parallel arrays.

    Layout matches what ml_inference.js walks:
        l/r  children (-1 = leaf), f feature index, t threshold (internal only)
        v    per-node output — leaf value for regression, class distribution
             for classification (internal nodes are null)
    """
    n = tree.node_count
    left = tree.children_left.tolist()
    right = tree.children_right.tolist()
    feature = tree.feature.tolist()
    threshold = tree.threshold.tolist()
    value = np.asarray(tree.value)
    if value.ndim == 3:                       # (n_nodes, n_outputs, n_classes)
        value = value[:, 0, :]
    value = value.tolist()

    feats, thr, vals = [], [], []
    for i in range(n):
        is_leaf = left[i] == -1
        feats.append(None if is_leaf else int(feature[i]))
        thr.append(None if is_leaf else _num(threshold[i]))
        # Leaves keep their value; internal nodes would just bloat the bundle.
        vals.append([_num(x) for x in value[i]] if is_leaf else None)
    return {"l": left, "r": right, "f": feats, "t": thr, "v": vals}


def _prep_dict(pipe) -> dict:
    """Export the fitted ColumnTransformer: impute -> scale -> one-hot."""
    prep = pipe.named_steps["prep"]
    named = {name: (trans, cols) for name, trans, cols in prep.transformers_}

    num_pipe = prep.named_transformers_["num"]
    imputer = num_pipe.named_steps["imputer"]
    scaler = num_pipe.named_steps["scaler"]
    cat_pipe = prep.named_transformers_["cat"]
    onehot = cat_pipe.named_steps["onehot"]

    num_cols = list(named["num"][1])
    cat_cols = list(named["cat"][1])
    return {
        "num": {
            "columns": num_cols,
            # medians = SimpleImputer(strategy='median') statistics_
            "medians": [_num(v) for v in np.asarray(imputer.statistics_).ravel()],
            "mean": [_num(v) for v in np.asarray(scaler.mean_).ravel()],
            "scale": [_num(v) for v in np.asarray(scaler.scale_).ravel()],
        },
        "cat": {
            "column": cat_cols[0] if cat_cols else "category",
            "categories": [str(c) for c in onehot.categories_[0]],
            # handle_unknown='ignore' => an unseen category becomes all zeros,
            # which is exactly what ml_inference.js does.
            "handle_unknown": "ignore",
            "missing_fill": "__missing__",
        },
    }


def _estimator_dict(est):
    name = type(est).__name__
    if name not in SUPPORTED_ESTIMATORS:
        raise UnsupportedEstimator(
            f"{name} cannot be evaluated by ml_inference.js "
            f"(supported: {', '.join(SUPPORTED_ESTIMATORS)})"
        )

    if name.startswith("GradientBoosting"):
        init = getattr(est, "init_", None)
        constant = getattr(init, "constant_", None)
        if constant is None:
            raise UnsupportedEstimator("gradient boosting has no constant init_")
        return {
            "family": name,
            "init": _num(np.asarray(constant).ravel()[0]),
            "learning_rate": _num(est.learning_rate),
            "n_estimators": int(est.n_estimators_),
            "trees": [_tree_arrays(t.tree_) for t in est.estimators_[:, 0]],
        }

    if name.startswith("DecisionTree"):
        return {"family": name, "tree": _tree_arrays(est.tree_)}

    # LogisticRegression: z = coef . x + intercept, then softmax.
    return {
        "family": name,
        "coef": np.asarray(est.coef_, dtype=float).tolist(),
        "intercept": np.asarray(est.intercept_, dtype=float).tolist(),
    }


def export_task(task_dir: Path) -> dict | None:
    """Load one saved pipeline and return its browser-exportable form."""
    import joblib

    pipe_path = task_dir / "pipeline.joblib"
    meta_path = task_dir / "meta.json"
    if not pipe_path.exists() or not meta_path.exists():
        return None
    pipe = joblib.load(pipe_path)
    meta = json.loads(meta_path.read_text())
    est = pipe.named_steps["model"]

    out = {
        "task": task_dir.name,
        "model": meta.get("model") or type(est).__name__,
        "features": meta.get("features") or [],
        "target": meta.get("target"),
        "labels": meta.get("labels"),
        "n_train": meta.get("n_train"),
        "n_val": meta.get("n_val"),
        "n_test": meta.get("n_test"),
        "test_metrics": _scalar_metrics(meta.get("test_metrics")),
        "sklearn_estimator": type(est).__name__,
    }
    # Class order of the fitted estimator (alphabetical, as sklearn stores it).
    # `labels` (meta.json) is the tier order used for display; both are exported
    # so the browser engine can key probabilities and the UI can order the bars.
    if getattr(est, "classes_", None) is not None:
        out["classes"] = [str(c) for c in est.classes_]

    out["prep"] = _prep_dict(pipe)
    out.update(_estimator_dict(est))
    return out


# --------------------------------------------------------------------------
# parity fixtures: sklearn's own answers, to prove the JS engine matches
# --------------------------------------------------------------------------
def _row_for_task(task: str, case: dict) -> dict:
    """Build the single-row frame exactly the way app.py does.

    Crucially the category is normalized with clean.py's rule 9 first — that is
    what `/api/predict/*` does before it touches the encoder, so the fixtures
    pin the same behaviour (a hand-typed "education" must score like "Education",
    which ml_inference.js reproduces with its own normalizeCategory).
    """
    from clean import clean_category

    category = clean_category(case["category"])
    row = {
        "category": category if category else case["category"],
        "size_mb": np.nan if case.get("size_mb") is None else float(case["size_mb"]),
        "price": 0.0 if case.get("price") is None else float(case["price"]),
        "price_is_positive": 1.0 if (case.get("price") or 0) > 0 else 0.0,
    }
    if task == "m1_rating" or task == "m2_tier_with_reviews":
        row["reviews_log"] = float(np.log1p(case.get("reviews") or 0))
    return row


def make_parity_cases(models: dict, n_cases: int = 60, seed: int = 20240621) -> dict:
    """Deterministic inputs + the sklearn pipeline's own predictions."""
    import joblib
    import pandas as pd

    rng = np.random.default_rng(seed)
    cases: dict[str, list] = {}

    for key, _task_dir, _kind in TASKS:
        model = models.get(key)
        if not model:
            continue
        pipe = joblib.load(ART / key / "pipeline.joblib")
        meta = json.loads((ART / key / "meta.json").read_text())
        cats = model["prep"]["cat"]["categories"]
        rows, expected = [], []

        for i in range(n_cases):
            # Mix real categories, unseen ones and messy casing so the JS
            # normalization + unknown-category path is exercised too.
            roll = i % 6
            if roll == 3:
                cat = "Totally Unseen Category"
            elif roll == 4:
                cat = str(cats[int(rng.integers(len(cats)))]).lower()
            elif roll == 5:
                cat = str(cats[int(rng.integers(len(cats)))]).replace(" ", "_")
            else:
                cat = str(cats[int(rng.integers(len(cats)))])

            case = {
                "category": cat,
                "size_mb": None if i % 7 == 0 else round(float(rng.uniform(0.5, 300)), 3),
                "price": None if i % 5 == 0 else round(float(rng.choice([0.0, 0.99, 2.49, 9.99, 39.99])), 2),
            }
            if "reviews_log" in (meta.get("features") or []):
                case["reviews"] = None if i % 3 == 0 else int(rng.integers(0, 5_000_000))

            X = pd.DataFrame([_row_for_task(key, case)])[meta["features"]]
            if key == "m1_rating":
                expected.append(round(float(pipe.predict(X)[0]), 10))
            else:
                proba = pipe.predict_proba(X)[0]
                labels = [str(c) for c in pipe.classes_]
                expected.append({
                    "tier": labels[int(np.argmax(proba))],
                    "probabilities": {lbl: round(float(p), 10) for lbl, p in zip(labels, proba)},
                })
            rows.append(case)

        cases[key] = {"cases": rows, "expected": expected}
    return cases


# --------------------------------------------------------------------------
# dataset bundle
# --------------------------------------------------------------------------
def build_dataset_bundle(apps_json: Path = APPS_JSON) -> dict:
    """Columnar mirror of apps.json.

    Row-object JSON repeats every key 40,000 times; storing each field as one
    array (with a dictionary for low-cardinality strings) roughly halves the
    payload while expanding back to byte-identical rows at load time.
    """
    payload = json.loads(apps_json.read_text())
    rows = payload.get("rows") or []
    keys: list[str] = []
    for r in rows:
        for k in r.keys():
            if k not in keys:
                keys.append(k)

    columns: dict = {}
    for k in keys:
        values = [r.get(k) for r in rows]
        strings = [v for v in values if isinstance(v, str)]
        # Dictionary-encode only when it actually saves space.
        if strings and len(strings) == len(values):
            uniq = sorted(set(values))
            if len(uniq) <= max(64, len(values) // 8):
                index = {v: i for i, v in enumerate(uniq)}
                columns[k] = {"dict": uniq, "data": [index[v] for v in values]}
                continue
        columns[k] = {"data": values}

    return {
        "source": payload.get("source"),
        "is_sample": payload.get("is_sample"),
        "sampling": payload.get("sampling"),
        "generated_at": payload.get("generated_at"),
        "report": payload.get("report") or {},
        "row_count": len(rows),
        "columns": columns,
        # So the UI can say what it is looking at, and the tests can assert it.
        "bundle_of": str(apps_json.relative_to(ROOT)),
    }


def expand_bundle_reference(bundle: dict) -> list[dict]:
    """Reference implementation of the JS expander (used by tests)."""
    cols = bundle["columns"]
    keys = list(cols.keys())
    n = len(cols["app"]["data"]) if "app" in cols else 0
    out = []
    for i in range(n):
        row = {}
        for k in keys:
            c = cols[k]
            row[k] = c["dict"][c["data"][i]] if "dict" in c else c["data"][i]
        out.append(row)
    return out


# --------------------------------------------------------------------------
# writers
# --------------------------------------------------------------------------
def write_models_bundle(verbose: bool = True) -> dict:
    import joblib  # noqa: F401  (imported for a clear error message)

    models, skipped = {}, []
    for key, task_dir, _kind in TASKS:
        path = ART / task_dir
        if not (path / "pipeline.joblib").exists():
            skipped.append(f"{key}: no pipeline yet")
            continue
        try:
            models[key] = export_task(path)
        except UnsupportedEstimator as exc:
            skipped.append(f"{key}: {exc}")

    if not models:
        raise SystemExit("browser_export: no exportable models found — run `python train_models.py` first.")

    cases = make_parity_cases(models)
    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "ml/artifacts/*/pipeline.joblib (exported by browser_export.py)",
        "note": ("The same fitted scikit-learn pipelines the FastAPI backend serves, "
                 "flattened so ml_inference.js can evaluate them in the browser. "
                 "No retraining, no approximation."),
        "models": models,
    }
    BROWSER_DIR.mkdir(parents=True, exist_ok=True)
    MODELS_BUNDLE.write_text(_js_assign("APEX_BROWSER_MODELS", payload), encoding="utf-8")
    PARITY_CASES.write_text(json.dumps({
        "generated_at": payload["generated_at"],
        "note": "Inputs plus the sklearn pipeline's own output — ml_inference.js must reproduce these exactly.",
        "tasks": cases,
    }, indent=1), encoding="utf-8")

    if verbose:
        print(f"  {MODELS_BUNDLE.relative_to(ROOT)}  "
              f"({MODELS_BUNDLE.stat().st_size / 1024:.0f} KB, {len(models)} model(s))")
        for key in models:
            m = models[key]
            trees = len(m.get("trees", [])) or (1 if "tree" in m else 0)
            print(f"      {key}: {m['sklearn_estimator']} · {trees} tree(s) · "
                  f"{len(m['prep']['cat']['categories'])} categories")
        print(f"  {PARITY_CASES.relative_to(ROOT)}  "
              f"({PARITY_CASES.stat().st_size / 1024:.0f} KB parity fixtures)")
        for s in skipped:
            print(f"      skipped — {s}")
    return payload


def write_dataset_bundle(verbose: bool = True) -> dict:
    if not APPS_JSON.exists():
        raise SystemExit("browser_export: data/apps.json not found — run `python clean.py` first.")
    payload = build_dataset_bundle(APPS_JSON)
    APPS_BUNDLE.write_text(_js_assign("APEX_APPS_PAYLOAD", payload), encoding="utf-8")

    # Fail loudly (and early, at export time) if the columnar round-trip is lossy.
    original = json.loads(APPS_JSON.read_text())["rows"]
    expanded = expand_bundle_reference(payload)
    if expanded != original:
        raise SystemExit("browser_export: dataset bundle round-trip mismatch — refusing to write.")

    if verbose:
        kb = APPS_BUNDLE.stat().st_size / 1024
        print(f"  {APPS_BUNDLE.relative_to(ROOT)}  ({kb:.0f} KB, "
              f"{payload['row_count']:,} rows, round-trip verified)")
    return payload


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1], formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data", action="store_true", help="only rebuild data/apps_bundle.js")
    ap.add_argument("--models", action="store_true", help="only rebuild the model bundle + parity fixtures")
    args = ap.parse_args()

    do_data = args.data or not args.models
    do_models = args.models or not args.data

    print("browser_export: writing browser bundles")
    try:
        if do_data:
            write_dataset_bundle()
        if do_models:
            write_models_bundle()
    except SystemExit:
        raise
    except ImportError as exc:
        print(f"  skipped ({exc}); install requirements.txt to generate bundles", file=sys.stderr)
        return 1
    print("browser_export: done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
